# Generated by Django 3.2.11 on 2022-01-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aproved_comment',
            new_name='approved_comment',
        ),
    ]
